  - name: Install remi release repositories
    ansible.builtin.package:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm 
      state: present
      disable_gpg_check: true
  - name: enable redis
    ansible.builtin.command: dnf module enable redis:remi-6.2 -y

  - name: Install redis
    ansible.builtin.package:
      name: redis
      state: present

  - name: Allowing remote connecions
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
      
  - name: Start & Enable redis
    ansible.builtin.service:
      name: redis
      state: started
      enabled: yes


